services:
  redis:
    image: redis:alpine
    container_name: url_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app_network

  cassandra:
    image: cassandra:latest
    container_name: url_cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES'"]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=MyDC
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
    ports:
      - "9042:9042"
    networks:
      - app_network

  # --- Serviços da Aplicação Atualizados ---

  app1:
    build:
      context: . # O contexto é a raiz (onde está o pyproject.toml)
      dockerfile: app/Dockerfile # O caminho para o Dockerfile
    container_name: url_app1
    # As variáveis de ambiente agora são lidas pelo config.py
    environment:
      - REDIS_HOST=redis
      - CASSANDRA_HOST=cassandra
    depends_on:
      redis:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    networks:
      - app_network

  app2:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: url_app2
    environment:
      - REDIS_HOST=redis
      - CASSANDRA_HOST=cassandra
    depends_on:
      redis:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    networks:
      - app_network

  # --- Nginx (Load Balancer) ---

  lb:
    image: nginx:latest
    container_name: url_nginx_lb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
